on:
  push:
    branches:
    - "*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker-practice/actions-setup-docker@1.0.4
    - run: make build
    - run: make build-vocabulary
    - name: GitHub Pages
      if: ${{ github.ref == 'refs/heads/master' }}
      uses: crazy-max/ghaction-github-pages@v2.1.1
      with:
        build_dir: extensions
        jekyll: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - uses: nelonoel/branch-name@v1.0.1
    - name: Publish preview
      uses: jsmrcaga/action-netlify-deploy@v1.5.0
      with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_MESSAGE: Preview ${{ env.BRANCH_NAME }}
          build_directory: extensions
          deploy_alias: ${{ env.BRANCH_NAME }}
          NETLIFY_DEPLOY_TO_PROD: ${{ env.BRANCH_NAME == 'master' }}

    - name: Status check
      uses: Sibz/github-status-action@v1.1.1
      with:
        authToken: ${{ secrets.GITHUB_TOKEN }}
        context: Netlify Site
        state: success
        target_url: https://${{ env.BRANCH_NAME }}--hydra-extensions.netlify.app
